/// <reference types="cypress" />

describe('Interações com a aba Buzz', () => {

    beforeEach('Visitar site, fazer login e validar o login', () => {
        cy.visit('https://opensource-demo.orangehrmlive.com/')
        cy.xpath('//div[@id="footer"]').should('contain', 'OrangeHRM 4.10.1')
        cy.xpath('//input[@id="txtUsername"]')
            .should('be.visible')
            .type('Admin')
            .should('have.value', 'Admin')
        cy.xpath('//input[@id="txtPassword"]')
            .should('be.visible')
            .type('admin123')
            .should('have.value', 'admin123')
        cy.xpath('//input[@id="btnLogin"]')
            .should('be.visible')
            .click()
        cy.xpath('//a[@id="welcome"]')
            .should('be.visible')
            .and('contain', 'Welcome')
    })

    it('Realizar uma postagem', () => {
        cy.intercept('POST', 'https://opensource-demo.orangehrmlive.com/index.php/buzz/addNewPost').as('waitPost')
        cy.xpath('//a[@id="menu_buzz_viewBuzz"]')
            .should('be.visible')
            .click()
        cy.xpath('//a[@id="status-tab-label"]')
            .should('be.visible')
            .and('have.text', 'Update Status')
        cy.xpath('//textarea[@id="createPost_content"]')
            .should('be.visible')
            .type('Olá, desejo a todos um ótimo dia!')
            .should('have.value', 'Olá, desejo a todos um ótimo dia!')
        cy.xpath('//input[@id="postSubmitBtn"]')
            .should('be.visible')
            .click()
        cy.wait('@waitPost')
        cy.xpath('//ul[@id="buzz"]//li[@class="singlePost"][1]//div[@class="lastLoadedPost"]')
            .invoke('attr', 'id').then(($value) => {
                cy.log($value)
                cy.xpath('//div[@id="postContent_'+ $value +'"]')
                    .should('be.visible')
                    .and('contain', 'Olá, desejo a todos um ótimo dia!')
            })     

    })


    it('Deletar uma postagem', () => {
        cy.intercept('POST', 'https://opensource-demo.orangehrmlive.com/index.php/buzz/addNewPost').as('waitPost')
        cy.intercept('POST', 'https://opensource-demo.orangehrmlive.com/index.php/buzz/deleteShare').as('waitResponse')
        cy.xpath('//a[@id="menu_buzz_viewBuzz"]')
            .should('be.visible')
            .click()
        cy.xpath('//a[@id="status-tab-label"]')
            .should('be.visible')
            .and('have.text', 'Update Status')
        cy.xpath('//textarea[@id="createPost_content"]')
            .should('be.visible')
            .type('Postar e excluir')
            .should('have.value', 'Postar e excluir')
        cy.xpath('//input[@id="postSubmitBtn"]')
            .should('be.visible')
            .click()
        cy.wait('@waitPost')
        cy.xpath('//ul[@id="buzz"]//li[@class="singlePost"][1]//div[@class="lastLoadedPost"]')
            .invoke('attr', 'id').then(($value) => {
                cy.log($value)
                cy.xpath('//div[@id="postContent_'+ $value +'"]')
                    .should('be.visible')
                    .and('contain', 'Postar e excluir')
                cy.xpath('//a[@class="account"][@id="'+ $value +'"]')
                    .should('be.visible')
                    .click()
                cy.xpath('//a[@class="deleteShare"][@id="deleteShare_'+ $value +'"]')
                    .should('be.visible')
                    .click()
                cy.xpath('//div[@class="modal-body message-box-modal-body"]//input[@id="delete_confirm"]')
                    .should('be.visible')
                    .click()
                cy.wait('@waitResponse').its('response.statusCode').should('equal', 200)
            })           

    })


    it('Editar uma postagem', () => {
        cy.intercept('POST', 'https://opensource-demo.orangehrmlive.com/index.php/buzz/addNewPost').as('waitPost')
        cy.intercept('POST', 'https://opensource-demo.orangehrmlive.com/index.php/buzz/editShare').as('waitResponse')
        cy.xpath('//a[@id="menu_buzz_viewBuzz"]')
            .should('be.visible')
            .click()
        cy.xpath('//a[@id="status-tab-label"]')
            .should('be.visible')
            .and('have.text', 'Update Status')
        cy.xpath('//textarea[@id="createPost_content"]')
            .should('be.visible')
            .type('Postar e editar')
            .should('have.value', 'Postar e editar')
        cy.xpath('//input[@id="postSubmitBtn"]')
            .should('be.visible')
            .click()
        cy.wait('@waitPost')
        cy.xpath('//ul[@id="buzz"]//li[@class="singlePost"][1]//div[@class="lastLoadedPost"]')
            .invoke('attr', 'id').then(($value) => {
                cy.log($value)
                cy.xpath('//div[@id="postContent_'+ $value +'"]')
                    .should('be.visible')
                    .should('contain', 'Postar e editar')
                cy.xpath('//a[@class="account"][@id="'+ $value +'"]')
                    .should('be.visible')
                    .click()
                cy.xpath('//a[@class="editShare"][@id="editShare_'+ $value +'"]')
                    .should('be.visible')
                    .click()
                cy.xpath('//div[@class="modal-body editPostModal-body"]//textarea[@id="editshareBox_'+ $value + '"]')
                    .should('be.visible')
                    .clear()
                    .type('Editado')
                    .should('have.value', 'Editado')
                cy.xpath('//div[@class="modal-body editPostModal-body"]//input[@id="btnEditShare_'+ $value + '"]')
                    .should('be.visible')
                    .click()
                cy.wait('@waitResponse').its('response.statusCode').should('equal', 200)
                cy.xpath('//div[@id="postContent_'+ $value +'"]')
                    .should('be.visible')
                    .and('contain', 'Editado')
            })         
    })
    
})